services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fastifydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./my-fastify-app
    ports:
      - "3000:3000"
    env_file:
      - ./my-fastify-app/.env
    depends_on:
      - db
    command: ["sh", "wait-for-it.sh", "db:5432", "--", "npm", "run", "dev"]
    volumes:
      - ./my-fastify-app:/app

  frontend:
    build: ./frontend
    ports:
      - "8000:8000"

volumes:
  postgres_data: